name: demo-tes-hybrid-cloud
channels:
  - conda-forge
  - bioconda
dependencies:
  - bash_kernel >=0.9.0
  - curl >=7.87.0
  - jq >=1.6
  - jupyterlab >=3.6.1
  - pip >=23.0
  - python >= 3.8.16
  - snakemake >= 7.21.0, <8
