urls:
  finlad: "https://csc.fi/o/csc-theme/images/csc-logo-teksti-fi.png"
  greece: "https://gsri.gov.gr/wp-content/uploads/2022/05/Athena_Horizontal-Ext_EN-page-001-3.jpg"
  czech: "https://www.mzv.cz/public/a8/13/d5/661666_637430_mzv_en.png"
  united_kindom: "http://britishfamily.co.uk/wp-content/uploads/2015/02/MADE_IN_BRITAIN_web_300x300.png"