from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider

localrules: all, download

# any other remote storage is possible as well e.g. FTP
# Remote storage has to be suported by Snakemake.
# https://snakemake.readthedocs.io/en/stable/snakefiles/remote_files.html
S3 = S3RemoteProvider(
    access_key_id="ACCESS_KEY_ID",
    secret_access_key="SECRET_ACCESS_KEY",
    endpoint_url="https://MY.S3_STORAGE.ORG")

# adjust to your own path
outfile_s3 = "BUCKET/PATH/outfile_smk_demo.txt"
remote_file_s3 = "BUCKET/PATH/news_archimedes_el.png"


rule all:
    input:
        file="results/outfile_local.txt"


rule getFile:
    output:
        file=S3.remote(remote_file_s3)
    shell:
        """
        curl 'https://www.sowi.hu-berlin.de/de/lehrbereiche/s_professuren/copy_of_wissenschaftsforschung/bilder/bih-logo.png' --output {output.file}
        """


rule processing:
    input:
        file=S3.remote(remote_file_s3)
    output:
        file=S3.remote(outfile_s3)
    shell:
        """
        openssl dgst -md5 {input.file} > md5.txt
        openssl dgst -sha1 {input.file} > sha1.txt
        openssl dgst -sha224 {input.file} > sha224.txt
        cat md5.txt sha1.txt sha224.txt > {output.file}
        """


rule download:
    input:
        file=S3.remote(outfile_s3)
    output:
        file="results/outfile_local.txt"
    shell:
        """
        sleep 3
        cp {input.file} {output.file}
        """
